module.exports = [
    `You have to send 1080 messages to get all your little legends to level 3 on this server.`,
    `Always scout your opponents boards in order to know which comp is still available.`,
    `If you are Diamond or higher, you will get the TFT Expert Role!`,
    `Hyperrolling is a very strong strategy if used correctly, you should learn it.`,
    `Every composition has it's very unique power - you should take advantage of that!`,
    `Sometimes you just don't get your desired champions. In this case you should just buy what you got!`,
    `Using an overlay can improve your performance!`,
    `You can find new friends on the server who you can play TFT with!`,
    `We have Discord Clans in League of Legends. Ask the moderators to invite you in!`,
    `The Orb of Enlightment now refreshes every 72 hours, so you have to play 5 games every 3 days!`,
    `Don't use Spear of Shojin on no or low mana units! The B.F. Sword and the Tear of the Goddess has much more value.`,
    `If you know that a lost round will cost you the game, move your little legend as far away as you can. This can be really impactful.`,
    `In carousel, try to go for an important item rather than a champion you could need.!`,
    `Spatula is still the strongest item that you can get, but use it with wisdom!`,
    `You can comeback even from 1 HP!`,
    `Mountain hex buffs are stacked each round, so use it for champions you will most likely use in late game!`,
    `There will four sets in TFT, which rotate, one after another.`,
    `Ocean Mages are stong.The Mystic gives Magic Resist for your whole team and can be really useful against them.`,
    `If you are in a 1v1, try to pick the units the opponent needs.Denying him his Level 3 Olaf could save your first place.`,
    `Don’t play Ranked TFT when you’re drunk.Just don’t.xd `,
    `A TFT App can be really useful if you’re new to the game or the set`,
    `TFT Mobile will be released early 2020. There are rumors about a beta in December`,
    `If you are in the carousel, use R to instantly look at your own board.`,
    `There are shortcuts on your keyboard for selling, rerolling and leveling.`,
    `TFT Patches release every 2 weeks on Wednesday.`,
    `Even Pro Players have games where they end up 7th or 8th.Just keep going!`,
    `Make sure you read the #announcements channel to stay up to date with coming tournaments or events!`,
]